// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';

import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI/migrations need a stable direct or session-pooled connection.
    // Runtime Prisma Client continues to use DATABASE_URL from schema.prisma.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"]!,
  },
});
